apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myapp-8f41"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myapp-8f41"
  template:
    metadata:
      labels:
        app: "myapp-8f41"
    spec:
      containers:
        - name: "myapp-8f41"
          image: "dregistrico.azurecr.io/myapp"
          ports:
          - containerPort: 8080